name: update dev from main branch
run-name: Update dev from ${{ github.ref}} (${{ github.sha}})
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  actions: write
jobs:
  update:
    uses: ./.github/workflows/reuseable-update-bucket.yml
    with:
      environment: dev
      bucket-name: dazl-dev-projects-storage
    secrets:
      aws-role-to-assume: ${{ secrets.AWS_RUNNER_ROLE }}
